Pin click version
An update to `click` causes `black` to fail with
`ImportError: cannot import name '_unicodefun' from 'click' (/Users/jimhays/.cache/pre-commit/repoef_0ghls/py_env-python3/lib/python3.10/site-packages/click/__init__.py)`

This pins `click` at a working version.

For more information, see:
https://github.com/dask/distributed/issues/6013