Update interfaces.py
Fix a bug:

```
        if output_filename is not None:
>           torchaudio.save(output_filename, enhanced, channels_first=False)
E           TypeError: save() missing 1 required positional argument: 'sample_rate'

/opt/homebrew/lib/python3.10/site-packages/speechbrain/pretrained/interfaces.py:2498: TypeError
```